### ISSUE TITLE
Failed to write matrix to stream

### ISSUE THREAD

**Issue by SamuelLarkin** [MontrealCorpusTools/Montreal-Forced-Aligner#284]
Hi,
  I'm trying to use `mfa` to align my own data as part of a preparation step for [FastSpeech2](https://github.com/ming024/FastSpeech2).  I've generated lab files for each of my wav files.  Now I'm trying to run
```bash
mfa \
   train \
      --debug \
      --verbose \
      --num_jobs \$OMP_NUM_THREADS \
      $raw_data \
      $lexicon \
      $preprocessed_data
```

But I'm getting the following error.

```bash
Traceback (most recent call last):
  File "/space/group/nrc_ict/project/pkgs/ubuntu18/gcc-7.3.0/miniconda3/envs/montreal-forced-aligner-2.0.0/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/space/group/nrc_ict/project/pkgs/ubuntu18/gcc-7.3.0/miniconda3/envs/montreal-forced-aligner-2.0.0/lib/python3.8/site-packages/montreal_forced_aligner/command_line/m
fa.py", line 348, in main
    run_train_corpus(args)
  File "/space/group/nrc_ict/project/pkgs/ubuntu18/gcc-7.3.0/miniconda3/envs/montreal-forced-aligner-2.0.0/lib/python3.8/site-packages/montreal_forced_aligner/command_line/t
rain_and_align.py", line 147, in run_train_corpus
    align_corpus(args, unknown_args)
  File "/space/group/nrc_ict/project/pkgs/ubuntu18/gcc-7.3.0/miniconda3/envs/montreal-forced-aligner-2.0.0/lib/python3.8/site-packages/montreal_forced_aligner/command_line/t
rain_and_align.py", line 99, in align_corpus
    a.train()
  File "/space/group/nrc_ict/project/pkgs/ubuntu18/gcc-7.3.0/miniconda3/envs/montreal-forced-aligner-2.0.0/lib/python3.8/site-packages/montreal_forced_aligner/aligner/traina
ble.py", line 78, in train
    trainer.init_training(identifier, self.temp_directory, self.corpus, self.dictionary, previous)
  File "/space/group/nrc_ict/project/pkgs/ubuntu18/gcc-7.3.0/miniconda3/envs/montreal-forced-aligner-2.0.0/lib/python3.8/site-packages/montreal_forced_aligner/trainers/monop
hone.py", line 92, in init_training
    compile_train_graphs(self.train_directory, dictionary.output_directory,
  File "/space/group/nrc_ict/project/pkgs/ubuntu18/gcc-7.3.0/miniconda3/envs/montreal-forced-aligner-2.0.0/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessin
g/alignment.py", line 190, in compile_train_graphs
    run_mp(compile_train_graphs_func, jobs, log_directory)
  File "/space/group/nrc_ict/project/pkgs/ubuntu18/gcc-7.3.0/miniconda3/envs/montreal-forced-aligner-2.0.0/lib/python3.8/site-packages/montreal_forced_aligner/multiprocessin
g/helper.py", line 89, in run_mp                                                                                                                                                 parse_logs(log_directory)                                                                                                                                                  File "/space/group/nrc_ict/project/pkgs/ubuntu18/gcc-7.3.0/miniconda3/envs/montreal-forced-aligner-2.0.0/lib/python3.8/site-packages/montreal_forced_aligner/helper.py", li
ne 219, in parse_logs
    raise KaldiProcessingError(error_logs)
montreal_forced_aligner.exceptions.KaldiProcessingError: There was one or more errors when running Kaldi binaries.
```

If I run `mfa validate raw_data/ ../../corpora//lexicon.txt` I get an output that states that everything looks good.

```
INFO - Setting up corpus information...
INFO - Parsing dictionary without pronunciation probabilities without silence probabilities
INFO - Creating dictionary information...
INFO - Setting up training data...
Generating base features (mfcc)...
Calculating CMVN...
INFO -
    =========================================Corpus=========================================
    1817 sound files
    1817 sound files with .lab transcription files
    0 sound files with TextGrids transcription files
    0 additional sound files ignored (see below)
    2 speakers
    1817 utterances
    6890.430 seconds total duration

    DICTIONARY
    ----------
    There were no missing words from the dictionary. If you plan on using the a model trained on this dataset to align other datasets in the future, it is recommended that there be at least some missing words.

    SOUND FILE READ ERRORS
    ----------------------
    There were no sound files that could not be read. There were no sound files that had unsupported bit depths.

    FEATURE CALCULATION
    -------------------
    There were no utterances missing features.

    FILES WITHOUT TRANSCRIPTIONS
    ----------------------------
    There were no sound files missing transcriptions.

    TRANSCRIPTIONS WITHOUT FILES
    --------------------
    There were no transcription files missing sound files.

    TEXTGRID READ ERRORS
    --------------------
    There were no issues reading TextGrids.

    UNREADABLE TEXT FILES
    --------------------
    There were no issues reading text files.

INFO - Initializing training for mono...
montreal_forced_aligner.exceptions.KaldiProcessingError: There was one or more errors when running Kaldi binaries.
```

If I go under my `Document/MFA/corpus` and look at the logs, there is a file `mono/log/init.log` that contains more details about the error.

```
/home/sam037/Documents/MFA/thirdparty/bin/gmm-init-mono --shared-phones=/home/sam037/Documents/MFA/Mohawk/dictionary/phones/sets.int '--train-feats=ark,s,cs:apply-cmvn --utt2spk=ark:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/utt2spk.0 scp:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/cmvn.0.scp scp:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/feats.0.scp ark:- | add-deltas ark:- ark:- | subset-feats --n=10 ark:- ark:-| ' /home/sam037/Documents/MFA/Mohawk/dictionary/topo 39 /home/sam037/Documents/MFA/Mohawk/mono/0.mdl /home/sam037/Documents/MFA/Mohawk/mono/tree
add-deltas ark:- ark:-
subset-feats --n=10 ark:- ark:-
apply-cmvn --utt2spk=ark:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/utt2spk.0 scp:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/cmvn.0.scp scp:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/feats.0.scp ark:-
ERROR (add-deltas[5.5]:Write():matrix/kaldi-matrix.cc:1407) Failed to write matrix to stream
WARNING (add-deltas[5.5]:Write():util/kaldi-holder-inl.h:57) Exception caught writing Table object. kaldi::KaldiFatalError
WARNING (add-deltas[5.5]:Write():util/kaldi-table-inl.h:1057) Write failure to standard output
ERROR (add-deltas[5.5]:Write():util/kaldi-table-inl.h:1515) Error in TableWriter::Write
WARNING (add-deltas[5.5]:Close():util/kaldi-table-inl.h:1089) Error closing stream: wspecifier is ark:-
ERROR (add-deltas[5.5]:~TableWriter():util/kaldi-table-inl.h:1539) Error closing TableWriter [in destructor].
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
ERROR (apply-cmvn[5.5]:Write():matrix/kaldi-matrix.cc:1407) Failed to write matrix to stream
WARNING (apply-cmvn[5.5]:Write():util/kaldi-holder-inl.h:57) Exception caught writing Table object. kaldi::KaldiFatalError
WARNING (apply-cmvn[5.5]:Write():util/kaldi-table-inl.h:1057) Write failure to standard output
ERROR (apply-cmvn[5.5]:Write():util/kaldi-table-inl.h:1515) Error in TableWriter::Write
WARNING (apply-cmvn[5.5]:Close():util/kaldi-table-inl.h:1089) Error closing stream: wspecifier is ark:-
ERROR (apply-cmvn[5.5]:~TableWriter():util/kaldi-table-inl.h:1539) Error closing TableWriter [in destructor].
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
```

If I try to manually run the first half of the command, I don't get any error message.

```bash
../thirdparty/bin/apply-cmvn \
  --utt2spk=ark:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/utt2spk.0 \
  scp:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/cmvn.0.scp \
  scp:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/feats.0.scp \
  ark:- \
| ../thirdparty/bin/add-deltas ark:- ark:- \
>  /dev/null

../thirdparty/bin/apply-cmvn --utt2spk=ark:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/utt2spk.0 scp:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/cmvn.0.scp scp:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/feats.0.scp ark:-
../thirdparty/bin/add-deltas ark:- ark:-
LOG (apply-cmvn[5.5]:main():featbin/apply-cmvn.cc:162) Applied cepstral mean normalization to 1575 utterances, errors on 0
```

If I try to add `add-deltas` then I get an error message.

```bash
../thirdparty/bin/apply-cmvn \
  --utt2spk=ark:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/utt2spk.0 \
  scp:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/cmvn.0.scp \
  scp:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/feats.0.scp \
  ark:- \
| ../thirdparty/bin/add-deltas ark:- ark:- \
| ../thirdparty/bin/subset-feats --n=10 ark:- ark:- > /dev/null

../thirdparty/bin/subset-feats --n=10 ark:- ark:-
../thirdparty/bin/apply-cmvn --utt2spk=ark:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/utt2spk.0 scp:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/cmvn.0.scp scp:/home/sam037/Documents/MFA/Mohawk/corpus_data/split2/feats.0.scp ark:-
../thirdparty/bin/add-deltas ark:- ark:-
ERROR (add-deltas[5.5]:Write():matrix/kaldi-matrix.cc:1407) Failed to write matrix to stream
WARNING (add-deltas[5.5]:Write():util/kaldi-holder-inl.h:57) Exception caught writing Table object. kaldi::KaldiFatalError
WARNING (add-deltas[5.5]:Write():util/kaldi-table-inl.h:1057) Write failure to standard output
ERROR (add-deltas[5.5]:Write():util/kaldi-table-inl.h:1515) Error in TableWriter::Write
WARNING (add-deltas[5.5]:Close():util/kaldi-table-inl.h:1089) Error closing stream: wspecifier is ark:-
ERROR (add-deltas[5.5]:~TableWriter():util/kaldi-table-inl.h:1539) Error closing TableWriter [in destructor].
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
ERROR (apply-cmvn[5.5]:Write():matrix/kaldi-matrix.cc:1407) Failed to write matrix to stream
WARNING (apply-cmvn[5.5]:Write():util/kaldi-holder-inl.h:57) Exception caught writing Table object. kaldi::KaldiFatalError
WARNING (apply-cmvn[5.5]:Write():util/kaldi-table-inl.h:1057) Write failure to standard output
ERROR (apply-cmvn[5.5]:Write():util/kaldi-table-inl.h:1515) Error in TableWriter::Write
WARNING (apply-cmvn[5.5]:Close():util/kaldi-table-inl.h:1089) Error closing stream: wspecifier is ark:-
ERROR (apply-cmvn[5.5]:~TableWriter():util/kaldi-table-inl.h:1539) Error closing TableWriter [in destructor].
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
```

How can I fix this error?

Using version: 2.0.0a15

**Comment by SamuelLarkin** [comment]
The error message is misleading because the stack trace shows `add-deltas` and `apply-cmvn` but in reality, if we run the command the first part of the command `apply-cmvn.... | add-deltas` without `subset-feats`, the process works fine.  It is when we add the third component that it fails (`subset-feats`).  The stack trace must be because the pipe gets broken.

**Comment by SamuelLarkin** [comment]
I've been trying to debut this and I found some hint.  I have several wav files, more than 10.  If I run the trio of commands that fail, it looks like `subset-feats` is only processing the first 10 files.  If I add `--n=14` to `subset-feats` the pipeline fails after 14 inputs (wav).

```bash
{ 
  ~/Documents/MFA/thirdparty/bin/apply-cmvn \
    --utt2spk=ark:./MFA/Mohawk/corpus_data/split2/utt2spk.1 \
    scp:./MFA/Mohawk/corpus_data/split2/cmvn.1.scp \
    scp:./MFA/Mohawk/corpus_data/split2/feats.1.scp \
    ark:- \
  | ~/Documents/MFA/thirdparty/bin/add-deltas ark:- ark:- ; \
} \
| ~/Documents/MFA/thirdparty/bin/subset-feats \
  --n=14 \
  ark:- \
  ark:- \
| grep -c jon-ch
```

Where `jon-ch` is a prefix of all my files.

Then I get 14.

So why is mfa only handling the first 10 inputs?

**Comment by mmcauliffe** [comment]
Can you try upgrading MFA via `pip install -U montreal_forced_aligner` and rerunning? The monophone initialization should just use 10 utterances in order to not process a ton, but maybe something about your dataset makes the timing not right with the executables further down the pipeline. The pipes breaking aren't a huge deal, so they shouldn't be throwing such an error.  I redid it so that it should avoid breaking pipes and logging it, so that should fix the issue?

**Comment by SamuelLarkin** [comment]
Thanks for your help.

I've updated to the latest version `2.0.0a16` but I'm still getting an error

```bash
/home/sam037/Documents/MFA/thirdparty/bin/subset-feats \
  --n=10 \
  'ark,s,cs:~/Documents/MFA/thirdparty/bin/apply-cmvn --utt2spk=ark:./MFA.2.0.0a16/Mohawk/corpus_data/split2/utt2spk.0 scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/cmvn.0.scp scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/feats.0.scp ark:- | ~/Documents/MFA/thirdparty/bin/add-deltas ark:- ark:- |' \
  ark:./MFA.2.0.0a16/Mohawk/mono/temp_feats
/home/sam037/Documents/MFA/thirdparty/bin/subset-feats --n=10 'ark,s,cs:~/Documents/MFA/thirdparty/bin/apply-cmvn --utt2spk=ark:./MFA.2.0.0a16/Mohawk/corpus_data/split2/utt2spk.0 scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/cmvn.0.scp scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/feats.0.scp ark:- | ~/Documents/MFA/thirdparty/bin/add-deltas ark:- ark:- |' ark:./MFA.2.0.0a16/Mohawk/mono/temp_feats
/home/sam037/Documents/MFA/thirdparty/bin/add-deltas ark:- ark:-
/home/sam037/Documents/MFA/thirdparty/bin/apply-cmvn --utt2spk=ark:./MFA.2.0.0a16/Mohawk/corpus_data/split2/utt2spk.0 scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/cmvn.0.scp scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/feats.0.scp ark:-
ERROR (add-deltas[5.5]:Write():matrix/kaldi-matrix.cc:1407) Failed to write matrix to stream
WARNING (add-deltas[5.5]:Write():util/kaldi-holder-inl.h:57) Exception caught writing Table object. kaldi::KaldiFatalError
WARNING (add-deltas[5.5]:Write():util/kaldi-table-inl.h:1057) Write failure to standard output
ERROR (add-deltas[5.5]:Write():util/kaldi-table-inl.h:1515) Error in TableWriter::Write
WARNING (add-deltas[5.5]:Close():util/kaldi-table-inl.h:1089) Error closing stream: wspecifier is ark:-
ERROR (add-deltas[5.5]:~TableWriter():util/kaldi-table-inl.h:1539) Error closing TableWriter [in destructor].
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
ERROR (apply-cmvn[5.5]:Write():matrix/kaldi-matrix.cc:1407) Failed to write matrix to stream
WARNING (apply-cmvn[5.5]:Write():util/kaldi-holder-inl.h:57) Exception caught writing Table object. kaldi::KaldiFatalError
WARNING (apply-cmvn[5.5]:Write():util/kaldi-table-inl.h:1057) Write failure to standard output
ERROR (apply-cmvn[5.5]:Write():util/kaldi-table-inl.h:1515) Error in TableWriter::Write
WARNING (apply-cmvn[5.5]:Close():util/kaldi-table-inl.h:1089) Error closing stream: wspecifier is ark:-
ERROR (apply-cmvn[5.5]:~TableWriter():util/kaldi-table-inl.h:1539) Error closing TableWriter [in destructor].
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
sh: line 1:  2626 Aborted                 ~/Documents/MFA/thirdparty/bin/apply-cmvn --utt2spk=ark:./MFA.2.0.0a16/Mohawk/corpus_data/split2/utt2spk.0 scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/cmvn.0.scp scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/feats.0.scp ark:-
      2627                       | ~/Documents/MFA/thirdparty/bin/add-deltas ark:- ark:-
WARNING (subset-feats[5.5]:Close():util/kaldi-io.cc:515) Pipe ~/Documents/MFA/thirdparty/bin/apply-cmvn --utt2spk=ark:./MFA.2.0.0a16/Mohawk/corpus_data/split2/utt2spk.0 scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/cmvn.0.scp scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/feats.0.scp ark:- | ~/Documents/MFA/thirdparty/bin/add-deltas ark:- ark:- | had nonzero return status 34304
```

Where the pipe returns a nonzero return status because the pipe gets broken because we only handle the first 10 utterances.

```bash
~/Documents/MFA/thirdparty/bin/apply-cmvn \
  --utt2spk=ark:./MFA.2.0.0a16/Mohawk/corpus_data/split2/utt2spk.0 \
  scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/cmvn.0.scp \
  scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/feats.0.scp \
  ark:- \
|  ~/Documents/MFA/thirdparty/bin/subset-feats \
  --n=1011 \
  ark:- \
  ark:- \
| wc
/home/sam037/Documents/MFA/thirdparty/bin/apply-cmvn --utt2spk=ark:./MFA.2.0.0a16/Mohawk/corpus_data/split2/utt2spk.0 scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/cmvn.0.scp scp:./MFA.2.0.0a16/Mohawk/corpus_data/split2/feats.0.scp ark:-
/home/sam037/Documents/MFA/thirdparty/bin/subset-feats --n=1011 ark:- ark:-
63036
ERROR (apply-cmvn[5.5]:Write():matrix/kaldi-matrix.cc:1407) Failed to write matrix to stream
WARNING (apply-cmvn[5.5]:Write():util/kaldi-holder-inl.h:57) Exception caught writing Table object. kaldi::KaldiFatalError
WARNING (apply-cmvn[5.5]:Write():util/kaldi-table-inl.h:1057) Write failure to standard output
ERROR (apply-cmvn[5.5]:Write():util/kaldi-table-inl.h:1515) Error in TableWriter::Write
WARNING (apply-cmvn[5.5]:Close():util/kaldi-table-inl.h:1089) Error closing stream: wspecifier is ark:-
ERROR (apply-cmvn[5.5]:~TableWriter():util/kaldi-table-inl.h:1539) Error closing TableWriter [in destructor].
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
```


I'm on `ubuntu-18` using `Python 3.8.8`.

**Comment by mmcauliffe** [comment]
That is very odd.  Ok, some random debugging things:

1. Can you check that your disks are full?
2. Can you run the command with a `--clean` flag on it? (there might be some files that didn't get implicitly cleaned up from the last runs)
3. Can you provide more details about the data itself (i.e., how long are the audio files, what format, does this happen when running on the LibriSpeech example?)
4. A bit of a shot in the dark, but maybe try building Kaldi from scratch on your machine and collecting the binaries: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#building-platform-specific-binaries-from-scratch

Very puzzling, the error doesn't really give much information and I'm really not sure why the `subset-feats` command can't write to the stream.
