### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by fatchord** [MontrealCorpusTools/Montreal-Forced-Aligner#63]
Hi there, thanks for all your great work.

I seem to get this error sometimes when I run mfa_align: 
_______________________________________________________________
There was an error writing the TextGrid for track7, please see below:

Traceback (most recent call last):

  File "aligner/command_line/align.py", line 186, in <module>

  File "aligner/command_line/align.py", line 144, in validate_args
  File "aligner/command_line/align.py", line 139, in align_included_model
  File "aligner/command_line/align.py", line 119, in align_corpus
  File "aligner/aligner/pretrained.py", line 199, in export_textgrids
  File "aligner/multiprocessing.py", line 624, in convert_ali_to_textgrids
  File "aligner/textgrid.py", line 79, in ctm_to_textgrid
  File "textgrid/textgrid.py", line 409, in add
  File "textgrid/textgrid.py", line 176, in __init__
ValueError: (Decimal('3482.860'), Decimal('3482.827755102041'))
Failed to execute script align

**Comment by mmcauliffe** [comment]
I believe this issue has been fixed for version 1.1, so closing this for now.

**Comment by Jasonbaby** [comment]
I still suffer this problem at version 1.1.

**Comment by bm3n** [comment]
I am getting errors like this on roughly 60% of my inputs:

Traceback (most recent call last):
  File "aligner\textgrid.py", line 77, in ctm_to_textgrid
  File "site-packages\textgrid\textgrid.py", line 431, in add
  File "site-packages\textgrid\textgrid.py", line 189, in __init__
ValueError: (Decimal('112.020'), Decimal('111.96662131519274'))

**Comment by apkd** [comment]
Still getting this error on both 1.0.1 and 1.1:

* 1.0.1
```
Traceback (most recent call last):
  File "aligner\command_line\align.py", line 186, in <module>
  File "aligner\command_line\align.py", line 142, in validate_args
  File "aligner\command_line\align.py", line 115, in align_corpus
  File "aligner\aligner\pretrained.py", line 206, in export_textgrids
  File "aligner\multiprocessing.py", line 624, in convert_ali_to_textgrids
  File "aligner\textgrid.py", line 79, in ctm_to_textgrid
  File "site-packages\textgrid\textgrid.py", line 431, in add
  File "site-packages\textgrid\textgrid.py", line 189, in __init__
ValueError: (Decimal('30.520'), Decimal('30.5'))
[35508] Failed to execute script align
```

* 1.1.0 beta 2
```
The following exceptions were encountered during the ouput of the alignments to TextGrids:

test_audio_file:
Traceback (most recent call last):

  File "aligner\textgrid.py", line 81, in ctm_to_textgrid

  File "site-packages\textgrid\textgrid.py", line 431, in add

  File "site-packages\textgrid\textgrid.py", line 189, in __init__

ValueError: (Decimal('30.520'), Decimal('30.5'))
```

**Comment by peterolson** [comment]
I'm getting the same error. Is there any workaround?

```
The following exceptions were encountered during the ouput of the alignments to TextGrids:

5df63baacfdddd2058301f50:
Traceback (most recent call last):

  File "aligner\textgrid.py", line 81, in ctm_to_textgrid

  File "site-packages\textgrid\textgrid.py", line 431, in add

  File "site-packages\textgrid\textgrid.py", line 189, in __init__

ValueError: (Decimal('367.980'), Decimal('367.8853514739229'))

```

**Comment by binarythinktank** [comment]
was this ever resolved/worked-around? im still getting it...
i have 2609 files in a single folder, no subfolders. ranging from seconds to minutes.
all are encoded mono 22050, the files that are failing seem to be predominantly the larger ones above 1mb
i have no problem playing the files so they don't seem to be corrupt



There was an error writing the TextGrid for 291, please see below:
Traceback (most recent call last):
  File "aligner\command_line\align.py", line 186, in <module>
  File "aligner\command_line\align.py", line 142, in validate_args
  File "aligner\command_line\align.py", line 115, in align_corpus
  File "aligner\aligner\pretrained.py", line 206, in export_textgrids
  File "aligner\multiprocessing.py", line 624, in convert_ali_to_textgrids
  File "aligner\textgrid.py", line 79, in ctm_to_textgrid
  File "site-packages\textgrid\textgrid.py", line 431, in add
  File "site-packages\textgrid\textgrid.py", line 189, in __init__
ValueError: (Decimal('28.710'), Decimal('28.708571428571428'))
[22272] Failed to execute script align
